# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-03-12 10:59
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no', models.DecimalField(db_index=True, decimal_places=0, max_digits=20, unique=True, verbose_name='\u0421\u0447\u0435\u0442')),
            ],
            options={
                'ordering': ('org', 'bank'),
                'db_table': 'account',
                'verbose_name': '\u0420\u0430\u0441\u0447\u0435\u0442\u043d\u044b\u0439 \u0441\u0447\u0435\u0442',
                'verbose_name_plural': '\u0420\u0430\u0441\u0447\u0435\u0442\u043d\u044b\u0435 \u0441\u0447\u0435\u0442\u0430',
            },
        ),
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bik', models.BigIntegerField(unique=True, verbose_name='\u0411\u0418\u041a')),
                ('ks', models.DecimalField(decimal_places=0, max_digits=20, unique=True, verbose_name='\u041a\u0421')),
                ('sname', models.CharField(max_length=32, null=True, unique=True, verbose_name='\u041a\u0440\u0430\u0442\u043a\u043e\u0435 \u043d\u0430\u0438\u043c\u0435\u043d\u043e\u0432\u0430\u043d\u0438\u0435')),
                ('fname', models.CharField(max_length=254, verbose_name='\u041f\u043e\u043b\u043d\u043e\u0435 \u043d\u0430\u0438\u043c\u0435\u043d\u043e\u0432\u0430\u043d\u0438\u0435')),
                ('our', models.BooleanField(default=False, verbose_name='\u041d\u0430\u0448\u0435')),
            ],
            options={
                'ordering': ('sname',),
                'db_table': 'bank',
                'verbose_name': '\u0411\u0430\u043d\u043a',
                'verbose_name_plural': '\u0411\u0430\u043d\u043a\u0438',
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True, verbose_name='\u041d\u0430\u0438\u043c\u0435\u043d\u043e\u0432\u0430\u043d\u0438\u0435')),
            ],
            options={
                'ordering': ('name',),
                'db_table': 'client',
                'verbose_name': '\u041a\u043b\u0438\u0435\u043d\u0442',
                'verbose_name_plural': '\u041a\u043b\u0438\u0435\u043d\u0442\u044b',
            },
        ),
        migrations.CreateModel(
            name='Org',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inn', models.BigIntegerField(unique=True, verbose_name='\u0418\u041d\u041d')),
                ('type', models.BooleanField(default=False, verbose_name='\u0422\u0438\u043f')),
                ('sname', models.CharField(max_length=32, null=True, unique=True, verbose_name='\u041a\u0440\u0430\u0442\u043a\u043e\u0435 \u043d\u0430\u0438\u043c\u0435\u043d\u043e\u0432\u0430\u043d\u0438\u0435')),
                ('fname', models.CharField(max_length=254, verbose_name='\u041f\u043e\u043b\u043d\u043e\u0435 \u043d\u0430\u0438\u043c\u0435\u043d\u043e\u0432\u0430\u043d\u0438\u0435')),
                ('our', models.BooleanField(default=False, verbose_name='\u041d\u0430\u0448\u0435')),
            ],
            options={
                'ordering': ('sname',),
                'db_table': 'org',
                'verbose_name': '\u041e\u0440\u0433\u0430\u043d\u0438\u0437\u0430\u0446\u0438\u044f',
                'verbose_name_plural': '\u041e\u0440\u0433\u0430\u043d\u0438\u0437\u0430\u0446\u0438\u0438',
            },
        ),
        migrations.CreateModel(
            name='OrgClient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Client', verbose_name='\u041a\u043b\u0438\u0435\u043d\u0442')),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Org', verbose_name='\u041e\u0440\u0433\u0430\u043d\u0438\u0437\u0430\u0446\u0438\u044f')),
            ],
            options={
                'db_table': 'orgclient',
                'verbose_name': '\u041e\u0440\u0433\u0430\u043d\u0438\u0437\u0430\u0446\u0438\u044f \u041a\u043b\u0438\u0435\u043d\u0442\u0430',
                'verbose_name_plural': '\u041e\u0440\u0433\u0430\u043d\u0438\u0437\u0430\u0446\u0438\u0438 \u041a\u043b\u0438\u0435\u043d\u0442\u043e\u0432',
            },
        ),
        migrations.AddField(
            model_name='account',
            name='bank',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Bank', verbose_name='\u0411\u0430\u043d\u043a'),
        ),
        migrations.AddField(
            model_name='account',
            name='org',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Org', verbose_name='\u041e\u0440\u0433\u0430\u043d\u0438\u0437\u0430\u0446\u0438\u044f'),
        ),
        migrations.AlterUniqueTogether(
            name='orgclient',
            unique_together=set([('org', 'client')]),
        ),
        migrations.AlterUniqueTogether(
            name='account',
            unique_together=set([('org', 'bank')]),
        ),
    ]
