# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-03-14 09:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cash',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True, verbose_name='\u0414\u0430\u0442\u0430')),
                ('sum', models.DecimalField(db_index=True, decimal_places=2, max_digits=12, verbose_name='\u0421\u0443\u043c\u043c\u0430')),
                ('purpose', models.TextField(verbose_name='\u041d\u0430\u0437\u043d\u0430\u0447\u0435\u043d\u0438\u0435 \u043f\u043b\u0430\u0442\u0435\u0436\u0430')),
                ('done', models.BooleanField(default=False, verbose_name='\u0421\u0434\u0435\u043b\u0430\u043d\u043e')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Client', verbose_name='\u041a\u043b\u0438\u0435\u043d\u0442')),
            ],
            options={
                'ordering': ('date', 'client'),
                'db_table': 'cash',
                'verbose_name': '\u041a\u0430\u0441\u0441\u0430',
                'verbose_name_plural': '\u041a\u0430\u0441\u0441\u0430',
            },
        ),
        migrations.CreateModel(
            name='DocType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sname', models.CharField(max_length=16, unique=True, verbose_name='\u041a\u0440\u0430\u0442\u043a\u043e\u0435 \u043d\u0430\u0438\u043c\u0435\u043d\u043e\u0432\u0430\u043d\u0438\u0435')),
                ('fname', models.CharField(max_length=254, unique=True, verbose_name='\u041f\u043e\u043b\u043d\u043e\u0435 \u043d\u0430\u0438\u043c\u0435\u043d\u043e\u0432\u0430\u043d\u0438\u0435')),
            ],
            options={
                'ordering': ('sname',),
                'db_table': 'doctype',
                'verbose_name': '\u0422\u0438\u043f \u0434\u043e\u043a\u0443\u043c\u0435\u043d\u0442\u0430',
                'verbose_name_plural': '\u0422\u0438\u043f\u044b \u0434\u043e\u043a\u0443\u043c\u0435\u043d\u0442\u043e\u0432',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True, verbose_name='\u0414\u0430\u0442\u0430')),
                ('docno', models.CharField(db_index=True, max_length=32, verbose_name='\u2116 \u0434\u043e\u043a\u0443\u043c\u0435\u043d\u0442\u0430')),
                ('sum', models.DecimalField(db_index=True, decimal_places=2, max_digits=12, verbose_name='\u0421\u0443\u043c\u043c\u0430')),
                ('purpose', models.TextField(verbose_name='\u041d\u0430\u0437\u043d\u0430\u0447\u0435\u043d\u0438\u0435 \u043f\u043b\u0430\u0442\u0435\u0436\u0430')),
                ('client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Client', verbose_name='\u041a\u043b\u0438\u0435\u043d\u0442')),
                ('doctype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='money.DocType', verbose_name='\u0422\u0438\u043f \u0434\u043e\u043a\u0443\u043c\u0435\u043d\u0442\u0430')),
                ('our', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pays_our', to='core.Account', verbose_name='\u041d\u0430\u0448\u0438')),
                ('their', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pays_their', to='core.Account', verbose_name='\u0412\u0430\u0448\u0438')),
            ],
            options={
                'ordering': ('date', 'our', 'their', 'doctype', 'docno'),
                'db_table': 'payment',
                'verbose_name': '\u0421\u0442\u0440\u043e\u043a\u0430 \u0432\u044b\u043f\u0438\u0441\u043a\u0438',
                'verbose_name_plural': '\u0421\u0442\u0440\u043e\u043a\u0438 \u0432\u044b\u043f\u0438\u0441\u043a\u0438',
            },
        ),
        migrations.CreateModel(
            name='PayType',
            fields=[
                ('id', models.PositiveSmallIntegerField(primary_key=True, serialize=False, verbose_name='id')),
                ('sname', models.CharField(max_length=16, unique=True, verbose_name='\u041a\u0440\u0430\u0442\u043a\u043e\u0435 \u043d\u0430\u0438\u043c\u0435\u043d\u043e\u0432\u0430\u043d\u0438\u0435')),
                ('fname', models.CharField(max_length=254, unique=True, verbose_name='\u041f\u043e\u043b\u043d\u043e\u0435 \u043d\u0430\u0438\u043c\u0435\u043d\u043e\u0432\u0430\u043d\u0438\u0435')),
            ],
            options={
                'ordering': ('sname',),
                'db_table': 'paytype',
                'verbose_name': '\u0422\u0438\u043f \u043f\u043b\u0430\u0442\u0435\u0436\u0430',
                'verbose_name_plural': '\u0422\u0438\u043f\u044b \u043f\u043b\u0430\u0442\u0435\u0436\u0435\u0439',
            },
        ),
        migrations.AddField(
            model_name='payment',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='money.PayType', verbose_name='\u0422\u0438\u043f \u043f\u043b\u0430\u0442\u0435\u0436\u0430'),
        ),
        migrations.AlterUniqueTogether(
            name='payment',
            unique_together=set([('date', 'our', 'their', 'doctype', 'docno')]),
        ),
        migrations.AlterUniqueTogether(
            name='cash',
            unique_together=set([('date', 'client', 'sum')]),
        ),
    ]
